api_platform:
    mapping:
#         paths: ['%kernel.project_dir%/api/src/AppBundle/Entity']
        paths: ['%kernel.project_dir%/src/Document']
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
